[project]
name = "property-dealer-ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "aditya singh", email = "adityaainghmar04@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "alembic>=1.19.1",
    "apify-client>=3.2.0",
    "fastapi>=0.141.1",
    "groq>=1.7.0",
    "pgvector>=0.5.0",
    "psycopg2-binary>=2.9.12",
    "pwdlib[argon2]>=0.3.1",
    "pydantic-settings>=2.15.0",
    "pydantic[email]>=2.13.5",
    "python-dotenv>=1.2.3",
    "python-jose[cryptography]>=3.5.0",
    "python-multipart>=0.0.32",
    "qdrant-client>=1.19.0",
    "redis>=8.1.0",
    "requests>=2.34.2",
    "sentence-transformers>=6.0.1",
    "sqlalchemy>=2.0.52",
    "supabase>=2.31.0",
    "uvicorn>=0.52.4",
]

[project.scripts]
property-dealer-ai = "property_dealer_ai:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"
