"""add property owner

Revision ID: 466fb3ba819c
Revises: 114f6b8912cc
Create Date: 2026-09-02 04:05:37.860200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '466fb3ba819c'
down_revision: Union[str, Sequence[str], None] = '114f6b8912cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_properties_owner_id'), 'properties', ['owner_id'], unique=False)
    op.create_foreign_key(None, 'properties', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'properties', type_='foreignkey')
    op.drop_index(op.f('ix_properties_owner_id'), table_name='properties')
    op.drop_column('properties', 'owner_id')
    # ### end Alembic commands ###
