"""add property external id

Revision ID: fa6f07bc1fc5
Revises: 42f73d08981a
Create Date: 2026-09-04 00:34:56.197035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa6f07bc1fc5'
down_revision: Union[str, Sequence[str], None] = '42f73d08981a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('external_id', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_properties_external_id'), 'properties', ['external_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_properties_external_id'), table_name='properties')
    op.drop_column('properties', 'external_id')
    # ### end Alembic commands ###
